import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { ProjectContextProvider } from "@/context/ProjectContext";
import "../styles/app.css";
import "../styles/Reset.css";
import "../styles/globals.css";
import "./fontawesome.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("loading layout page...");
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ProjectContextProvider>{children}</ProjectContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
